#!/usr/bin/env bash
set -e

echo "🤖 Setting up OpenAI Codex CLI..."

# Check if codex is installed
if ! command -v codex &>/dev/null; then
  echo "❌ Codex CLI not found. Please install it first with 'brew install codex'"
  exit 1
fi

echo "✅ Codex CLI found: $(codex --version)"

# Check if already authenticated
if codex login --check &>/dev/null; then
  echo "✅ Codex is already authenticated"
else
  echo "🔐 Setting up Codex authentication..."
  echo "Please follow the authentication process:"
  codex login || true
fi

# Create basic config directory if it doesn't exist
mkdir -p ~/.codex

echo "📝 Creating basic Codex configuration..."
cat > ~/.codex/config.toml << 'EOF'
# OpenAI Codex CLI Configuration
# Generated by dotfiles setup

[general]
# Default model to use
model = "o1-mini"

[sandbox]
# Sandbox permissions for safety
default_policy = "workspace-write"

[approval]
# When to ask for approval
policy = "untrusted"
EOF

echo "✅ Codex setup complete!"
echo "💡 You can now use 'codex' to start an AI coding session"
echo "💡 Run 'codex --help' for more options"