#!/usr/bin/env bash
set -e

echo "🤖 Setting up OpenAI Codex CLI..."

# Check if codex is installed
if ! command -v codex &>/dev/null; then
  echo "❌ Codex CLI not found. Please install it first with 'brew install codex'"
  exit 1
fi

echo "✅ Codex CLI found: $(codex --version)"

# Skip auth — requires an interactive browser session; run 'codex login' manually after setup.
echo "ℹ️  Skipping Codex auth — run 'codex login' manually to authenticate"

# Create basic config directory if it doesn't exist
mkdir -p ~/.codex

# Only seed a config if one doesn't already exist, so we never clobber the
# user's customizations on re-runs.
if [[ ! -f ~/.codex/config.toml ]]; then
  echo "📝 Creating basic Codex configuration..."
  cat > ~/.codex/config.toml << 'EOF'
# OpenAI Codex CLI Configuration
# Generated by dotfiles setup.
# Set `model = "..."` to pin a model; otherwise Codex uses its current default.

[sandbox]
# Sandbox permissions for safety
default_policy = "workspace-write"

[approval]
# When to ask for approval
policy = "untrusted"
EOF
else
  echo "✅ Existing ~/.codex/config.toml kept (not overwritten)"
fi

echo "✅ Codex setup complete!"
echo "💡 You can now use 'codex' to start an AI coding session"
echo "💡 Run 'codex --help' for more options"